version: '3'
services:
  registry:
    image: nobrn/teastore-registry:dev1
    expose:
      - "8080"
  db:
    image: nobrn/teastore-db:dev1
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: nobrn/teastore-persistence:dev1
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    image: nobrn/teastore-auth:dev1
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    image: nobrn/teastore-image:dev1
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    image: nobrn/teastore-recommender:dev1
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    image: nobrn/teastore-webui:dev1
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"
